//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERPROTECT
    {
        public int userId { get; set; }
        public Nullable<int> userprotectKind { get; set; }
        public Nullable<int> userprotectModule { get; set; }
        public string userprotectLoginfo { get; set; }
        public Nullable<System.DateTime> userprotectOpttime { get; set; }
    }
}
