//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOCUMENT
    {
        public int documentId { get; set; }
        public Nullable<int> documentKind { get; set; }
        public string documentNote { get; set; }
        public Nullable<System.DateTime> documentTime { get; set; }
        public string documentUrl { get; set; }
    }
}
