//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AMMETER
    {
        public Nullable<int> siteId { get; set; }
        public int ammeterId { get; set; }
        public string ammeterName { get; set; }
        public string ammeterGroup { get; set; }
        public string ammeterModel { get; set; }
        public Nullable<double> ammeterRefpower { get; set; }
        public Nullable<double> ammeterOldload { get; set; }
        public Nullable<double> ammeterNewload { get; set; }
        public Nullable<double> ammeterRate { get; set; }
        public Nullable<double> ammeterAlarm { get; set; }
        public Nullable<int> ammeterStatus { get; set; }
        public Nullable<int> ammeterSwistatus { get; set; }
        public Nullable<double> ammeterLife { get; set; }
        public Nullable<System.DateTime> ammeterAcctime { get; set; }
        public string ammeterNote { get; set; }
    }
}
