//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIGCONTROL
    {
        public int ammeterId { get; set; }
        public Nullable<int> ammeterSwistatus { get; set; }
        public Nullable<double> sigcontrolIndtime { get; set; }
        public Nullable<System.TimeSpan> sigcontrolInsstatime { get; set; }
        public Nullable<System.TimeSpan> sigcontrolInsendtime { get; set; }
        public Nullable<double> sigcontrolAlacurup { get; set; }
        public Nullable<double> sigcontrolAlacurlow { get; set; }
    }
}
