//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CTRCONTROL
    {
        public int siteId { get; set; }
        public Nullable<int> ctrcontrolTimweek { get; set; }
        public Nullable<int> ctrcontrolLigweek { get; set; }
        public Nullable<System.TimeSpan> ctrcontrolTimopetime { get; set; }
        public Nullable<System.TimeSpan> ctrcontrolTimclotime { get; set; }
        public Nullable<double> ctrcontrolOpeligvalue { get; set; }
        public Nullable<double> ctrcontrolCloligvalue { get; set; }
        public Nullable<int> ctrcontrolLigvalsource { get; set; }
        public Nullable<System.DateTime> ctrcontrolSystime { get; set; }
        public Nullable<int> ctrcontrolSysweek { get; set; }
    }
}
