//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RUN
    {
        public int siteId { get; set; }
        public Nullable<double> runVolt { get; set; }
        public Nullable<double> runCurrent { get; set; }
        public Nullable<double> runStavalue { get; set; }
        public Nullable<System.DateTime> runFreshtime { get; set; }
    }
}
