//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SYSSET
    {
        public int syssetId { get; set; }
        public string syssetName { get; set; }
        public Nullable<double> syssetOpevalue { get; set; }
        public Nullable<double> syssetClovalue { get; set; }
        public Nullable<double> syssetAlatime { get; set; }
        public Nullable<double> syssetAlacurrent { get; set; }
        public string syssetNote { get; set; }
    }
}
