//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SITE
    {
        public int siteId { get; set; }
        public string siteName { get; set; }
        public string siteGroup { get; set; }
        public string siteModel { get; set; }
        public Nullable<int> siteStatus { get; set; }
        public Nullable<int> siteSwistatus { get; set; }
        public string siteIp { get; set; }
        public Nullable<System.DateTime> siteContime { get; set; }
        public string siteInssite { get; set; }
        public Nullable<System.DateTime> sitePurtime { get; set; }
        public Nullable<double> siteLife { get; set; }
        public Nullable<System.DateTime> siteAcctime { get; set; }
        public string siteNote { get; set; }
    }
}
