//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public Nullable<int> userSex { get; set; }
        public string userPwd { get; set; }
        public string userPhone { get; set; }
        public string userWechat { get; set; }
        public Nullable<int> userStatus { get; set; }
        public Nullable<System.DateTime> userLlogtime { get; set; }
        public Nullable<System.DateTime> userExptime { get; set; }
        public Nullable<int> userAut { get; set; }
        public string userNote { get; set; }
    }
}
