//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LampNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEVICEPROTECT
    {
        public int infoId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> siteId { get; set; }
        public Nullable<int> ammeterId { get; set; }
        public Nullable<int> deviceprotectKind { get; set; }
        public Nullable<int> deviceprotectModule { get; set; }
        public string deviceprotectLoginfo { get; set; }
        public Nullable<System.DateTime> deviceprotectOpttime { get; set; }
    }
}
